'use client';

import { ApolloProvider } from '@apollo/client';
import client from '../lib/client';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ApolloProvider client={client}>{children} </ApolloProvider>
      </body>
    </html>
  );
}
