import ApolloProvider from '../components/ApolloProvider';
import './globals.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <ApolloProvider>{children}</ApolloProvider>
      </body>
    </html>
  );
};

export default RootLayout;
